FROM nginx:1.27-alpine

WORKDIR /var/www/html

COPY public ./public

COPY docker/prod/nginx/nginx.conf /etc/nginx/nginx.conf
COPY docker/prod/nginx/default.conf.template /etc/nginx/templates/default.conf.template
COPY docker/prod/nginx/ssl/selfsigned.key /etc/nginx/ssl/selfsigned.key
COPY docker/prod/nginx/ssl/selfsigned.crt /etc/nginx/ssl/selfsigned.crt

RUN chmod 255 /etc/nginx/ssl/selfsigned.key /etc/nginx/ssl/selfsigned.crt

EXPOSE 80 443